winget install NexusMods.Vortex --ignore-security-hash --accept-package-agreements --accept-source-agreements
winget install TGRMNSoftware.BulkRenameUtility --ignore-security-hash --accept-package-agreements --accept-source-agreements
winget install Git.Git --ignore-security-hash --accept-package-agreements --accept-source-agreements
winget install GnuPG.GnuPG --ignore-security-hash --accept-package-agreements --accept-source-agreements
winget install GnuPG.Gpg4win --ignore-security-hash --accept-package-agreements --accept-source-agreements
winget install FlorianHeidenreich.Mp3tag --ignore-security-hash --accept-package-agreements --accept-source-agreements
winget install YACReader.YACReader --ignore-security-hash --accept-package-agreements --accept-source-agreements
winget install nepnep.neofetch-win --ignore-security-hash --accept-package-agreements --accept-source-agreements
winget install maforget.ComicRackCE.Nightly --ignore-security-hash --accept-package-agreements --accept-source-agreements
winget install AdrienAllard.FileConverter --ignore-security-hash --accept-package-agreements --accept-source-agreements
winget install GitHub.cli --ignore-security-hash --accept-package-agreements --accept-source-agreements
winget install GitHub.GitLFS --ignore-security-hash --accept-package-agreements --accept-source-agreements
winget install GitExtensionsTeam.GitExtensions --ignore-security-hash --accept-package-agreements --accept-source-agreements
winget install PrivateInternetAccess.PrivateInternetAccess --ignore-security-hash --accept-package-agreements --accept-source-agreements
winget install CodeSector.TeraCopy --ignore-security-hash --accept-package-agreements --accept-source-agreements
winget install JohnMacFarlane.Pandoc
winget install Neovim.Neovim --ignore-security-hash --accept-package-agreements --accept-source-agreements
winget install OpenMedia.4KVideoDownloaderPlus --ignore-security-hash --accept-package-agreements --accept-source-agreements
winget install dorssel.usbipd-win --ignore-security-hash --accept-package-agreements --accept-source-agreements
winget install MichaelTippach.ASIO4ALL --ignore-security-hash --accept-package-agreements --accept-source-agreements
winget install EPSON.EpsonScan2 --ignore-security-hash --accept-package-agreements --accept-source-agreements
winget install Syncplay.Syncplay --ignore-security-hash --accept-package-agreements --accept-source-agreements
winget install Trelby.Trelby --ignore-security-hash --accept-package-agreements --accept-source-agreements
winget install Oracle.JavaRuntimeEnvironment --ignore-security-hash --accept-package-agreements --accept-source-agreements
winget install ComicTagger.ComicTagger --ignore-security-hash --accept-package-agreements --accept-source-agreements
winget install DBeaver.DBeaver.Community --ignore-security-hash --accept-package-agreements --accept-source-agreements
winget install DevToys-app.DevToys --ignore-security-hash --accept-package-agreements --accept-source-agreements
winget install Gyan.FFmpeg --ignore-security-hash --accept-package-agreements --accept-source-agreements
winget install JesseDuffield.lazygit --ignore-security-hash --accept-package-agreements --accept-source-agreements
winget install LRCLIB.LRCGET --ignore-security-hash --accept-package-agreements --accept-source-agreements
winget install Modrinth.ModrinthApp --ignore-security-hash --accept-package-agreements --accept-source-agreements
winget install Spotify.Spotify --ignore-security-hash --accept-package-agreements --accept-source-agreements
winget install deepnight.LDtk --ignore-security-hash --accept-package-agreements --accept-source-agreements
winget install junegunn.fzf --ignore-security-hash --accept-package-agreements --accept-source-agreements
winget install marlocarlo.psmux --ignore-security-hash --accept-package-agreements --accept-source-agreements
winget install yt-dlp.FFmpeg --ignore-security-hash --accept-package-agreements --accept-source-agreements
winget install yt-dlp.yt-dlp --ignore-security-hash --accept-package-agreements --accept-source-agreements
